[package]
name = "temperature_unit_converter"
authors = ["fuwasegu <h_takeshita@yumemi.co.jp>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
